# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 23:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dataEHoraDeInicio', models.DateField(max_length=20)),
                ('endereco', models.CharField(max_length=150)),
                ('logotipo', models.CharField(max_length=40)),
                ('sigla', models.CharField(max_length=14)),
                ('eventoPrincipal', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validacao', models.BooleanField(default=False, verbose_name='Situação do pagamento de tickets')),
                ('Evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Evento_Inscricao', to='lpc_evento.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=10)),
                ('idade', models.IntegerField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('descricao', models.TextField()),
                ('valor', models.FloatField()),
                ('idEvento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Evento_Ticket', to='lpc_evento.Evento')),
            ],
        ),
        migrations.AddField(
            model_name='inscricao',
            name='Participante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pessoa_Inscricao', to='lpc_evento.Pessoa'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='Ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ticket_Inscricao', to='lpc_evento.Ticket'),
        ),
    ]
