# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpc_evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='validacao',
            field=models.CharField(max_length=40),
        ),
    ]
